name: Ant build CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up junit
      run: |
        sudo sh -c "echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/force-unsafe-io"
        sudo apt-get -qq install junit > /dev/null
    - name: Download freenet.jar
      run: |
        sudo mkdir -p ../fred/dist/
        wget https://github.com/hyphanet/fred/releases/download/build01497/freenet.jar -qO ../fred/dist/freenet.jar
        mkdir lib/
        wget https://repo.spring.io/plugins-release/com/db4o/com.db4o/7.7.67/com.db4o-7.7.67.jar -q O lib/com.db4o-7.7.67.jar
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Upload XMLLibrarian
      uses: actions/upload-artifact@v4
      with:
        name: plugin-XMLLibrarian
        path: dist/*
